services:
  - type: web
    name: whatsapp
    env: node
    branch: main
    repo: https://github.com/TcronebHackx-Md/whatsapp.git
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: false
    envVars:
      - key: SESSION_ID
        sync: false
      - key: DATABASE_URL
        sync: false
